# Generated by Django 2.2.16 on 2021-06-14 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(default='', max_length=200)),
                ('last_name', models.CharField(default='', max_length=200)),
                ('mobile', models.CharField(default='', max_length=100)),
                ('email', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(default='', max_length=100)),
                ('district', models.CharField(default='', max_length=100)),
                ('village', models.CharField(default='', max_length=100)),
                ('block', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
